parameters:
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt

    public.services: false

    backendHost: '%env(BACKEND_DSN)%'
    udp_logger_url: '%env(UDP_LOGGER_DSN)%'

    node_services_dirs:
        - '%kernel.project_dir%/config'
        - '%kernel.project_dir%/vendor/hanaboso/pipes-php-sdk/src/HbPFLongRunningNodeBundle/Resources'

    applications:
        - '%kernel.project_dir%/config'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: '%public.services%'
