hb_pf_application:
    resource: "@HbPFApplicationBundle/Controller"
    type: attribute

hb_pf_connector:
    resource: "@HbPFConnectorBundle/Controller"
    type: attribute

hb_pf_custom_node:
    resource: "@HbPFCustomNodeBundle/Controller"
    type: attribute

hb_pf_batch:
    resource: "@HbPFBatchBundle/Controller"
    type: attribute
