services:
    worker:
        image: worker:worker-tag
        build: ./docker
        user: ${DEV_UID}:${DEV_GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www:cached
        environment:
            # Envs for tests are load from .jest/testEnvs.ts
            JEST_DOCKER: 1
            APP_ENV: 'debug'
            TENANT_ID: 'docker'
            CRYPT_SECRET: 'ThisIsNotSoSecret'
            ORCHESTY_API_KEY: 'ThisIsNotSoSecretApiKey'
        command: sleep infinity
